---
title: "R Notebook"
output: html_notebook
---

```{r}
source("supply-demand-linear.R")
source("input_function.R")

```

Default vrijednosti

```{r}
linear_curve_2_ponts(c(2, 3, 5, 7), title="Supply")
linear_curve_2_ponts(c(2, 3, 5, 7), title="Supply", color = "green", pointsHidden=FALSE, lineCoordinateHidden=FALSE)

```

```{r}
linear_curve_2_ponts(c(3, 10, 6, 7), title = "Demand")
linear_curve_2_ponts(c(3, 10, 6, 7), title = "Demand", color = "red", pointsHidden=FALSE, lineCoordinateHidden=FALSE)
```

```{r}
linear_curve_2_ponts(c(1, 2, 5, 7), c(3, 9, 6, 4), title="Supply & Demand", color = "blue")
linear_curve_2_ponts(c(1, 2, 5, 7), c(3, 9, 6, 4), c(3, 2, 7, 7), title="Supply & Demand", color = "blue")
```

```{r}
linear_curve_2_characteristic(c(2, -5), c(-2, 10), title="Supply & Demand", color = "blue")
linear_curve_2_characteristic(c(2, -5), c(-2, 10), c(-2, 13), title="Supply & Demand", color = "blue")


```

```{r}
p1 <- c(1, 2, 5, 7)
p2 <- c(3, 9, 6, 4)

gg <- linear_curve_2_ponts(p1, p2, title="Supply & Demand", color = "blue")
find_intersection(p1, p2, gg)


```

```{r}
library(dplyr)
library(ggplot2)
library(Hmisc)

supply <- bezier(x = c(1, 8, 9), y = c(1, 5, 9)) %>% as.data.frame()
demand <- bezier(x = c(1, 3, 9), y = c(9, 3, 1)) %>% as.data.frame()

curve_N_ponts(supply, demand, title = "Supply & Demand")
```

```{r}
gg <- ggplot(mapping = aes(x = x, y = y)) +
  geom_path(data = supply, color = "#0073D9", linewidth = 1) +
  geom_path(data = demand, color = "#FF4036", linewidth = 1) +
  labs(x = "Quantity", y = "Price", title = "Supply & Demand") +
  coord_equal() +
  theme_classic()

curve_intersect(supply, demand, gg)
```
